# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Future of Networking
email: curtis@serverascode.com
description: >- # this means to ignore newlines until "baseurl:"
  Investigating new technologies in computer networking
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://futureofnetworking.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  futureofnetworking
author: fn

# Build settings
markdown: kramdown
#theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

#
# Podcast
#
# Based on https://github.com/joebuhlig/Jekyll-Podcast-Feed

podcast_url: http://futureofnetworking.github.io/podcasts
podcast_album_art: /img/podcast-cover.jpg
podcast_title: The Future of Networking
podcast_owner: Curtis Collicutt
podcast_email: curtis@serverascode.com
podcast_category: Technology
podcast_subcategory_one: Software How-To
podcast_subcategory_two: Gadgets
podcast_explicit: "no"
podcast_author: Curtis Collicutt
podcast_description: Investigating the future of computer networking.
podcast_summary: Investigating the future of computer networking.
podcast_subtitle: ""

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
